apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: teambit-db-data
  name: teambit-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
